### ISSUE TITLE
Use shared_configs repo for settings

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/digital_stacks_rails#62]
It appears that digital_stacks_rails does not keep its settings files (config/settings.yml + .yml files in config/settings/) under source control. Create a new branch in shared_configs for the settings, and update the deployment script(s) to pull the correct YAML file upon deployment.

**Comment by jmartin-sul** [comment]
created the shared_configs branches, will see if there's any puppet work that needs to be done.  my guess at this point from looking at the code is that digital_stacks_rails itself won't need any changes, since it already uses Rails settings, and since the shared_configs files won't step on any of the files that are checked into the digital_stacks_rails repo (both test and prod see their environment as `production`, and there's of course no `production.yml` in this repo).  and, unlike argo or dor-indexing-app, it seems like there's no need to create a shared_configs branch for laptop settings.

**Comment by jmartin-sul** [comment]
@eefahy walked me through the [puppet changes](https://github.com/sul-dlss/puppet/pull/698) and deployed the shared_configs branches to stacks -dev, -test, and -prod-[a|b].  stacks was restarted on each, and all appears to be well (-dev and -prod stacks are still serving images, -test is serving images and doing media stuff).  in addition, just to make sure it went smoothly, -dev and -test were redeployed, and there appeared to be no problem (using [master](https://github.com/sul-dlss/digital_stacks_rails/commit/85f541bb346ced9277a7d3e20f5d25ab41d4f77b) and [2016-07-19-test-deploy](https://github.com/sul-dlss/digital_stacks_rails/commit/bff0013acc3bb25450fca29336ada53e4042e1c2), respectively).  since prod is running a slightly older version of stacks, and since we don't want to deploy current master to prod before doing all the final testing required by the media work, we held off on re-deploying prod stacks code.

i think this one's all done.
